### ISSUE TITLE
Design: Create Color Scheme

### ISSUE THREAD

**Issue by alexng353** [AP-Students/website#21]
one fault in this PR I didn't mention is that the Tailwind theme is a mess. a color scheme would help before this is merged

_Originally posted by @elijah-wright in https://github.com/AP-Students/website/issues/20#issuecomment-2151494204_
            
Here's a shadcn-specific theme generator that we can use: https://gradient.page/tools/shadcn-ui-theme-generator

**Comment by EthanL06** [comment]
![image](https://github.com/AP-Students/website/assets/21349255/e2947bae-5704-4cb9-a0f2-860c5af3d8cd)

Color palette as documented in the Figma design file: https://www.figma.com/design/77n3v1bMUJ6CtoLzBrxvNl/AP(roject)-Website?node-id=449-27

**Comment by EthanL06** [comment]
Closed
