### ISSUE TITLE
Feature: Question Renderer

### ISSUE THREAD

**Issue by JSJ9** [AP-Students/website#24]
Create variables to determine question format (mcq or other), images, question text format, etc

- [x] establish a data type
- [ ] create a data-driven way to render abstract content as part of the question (use markdown)
- [x] create a data-driven component that renders out the question
  - [x] include both: multiselect; and
  - [x] multiple choice

**Comment by alexng353** [comment]
- [ ] establish a data type
- [ ] create a data-driven way to render abstract content as part of the question (use markdown)
- [ ] create a data-driven component that renders out the question
  - [ ] include both: multiselect; and
  - [ ] multiple choice

**Comment by JSJ9** [comment]
https://replit.com/@jimenezj9/questionrender-1

**Comment by manningwu07** [comment]
Compiled the code in VS Code - Check PR
