### ISSUE TITLE
Edit admin article creator UI design

### ISSUE THREAD

**Issue by manningwu07** [AP-Students/website#94]
I want the article creator page to have a backspace where they can navigate back to the subject homepage

Finally, subject homepage should look aestentically better rather than having the sidebar contain the links to the admin article creator.

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive

**Comment by manningwu07** [comment]
> try this
> 
> https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA Pass: changeme I put the necessary dlls in the archive

what is this? Can you take a screenshot of the design or like push a PR instead?
